# Generated by Django 5.2 on 2025-04-24 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аталышы')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='URL Аты (автоматтык)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category_images/', verbose_name='Сүрөтү')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Аты')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилиясы')),
                ('guest_phone', models.CharField(max_length=20, verbose_name='Байланыш телефону')),
                ('shipping_address', models.TextField(verbose_name='Жеткирүү дареги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн убактысы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убактысы')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Жалпы суммасы')),
                ('status', models.CharField(choices=[('pending', 'Күтүүдө'), ('processing', 'Иштелүүдө'), ('shipped', 'Жолдо'), ('delivered', 'Жеткирилди'), ('cancelled', 'Жокко чыгарылды')], default='pending', max_length=20, verbose_name='Абалы (статусу)')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
            ],
            options={
                'verbose_name': 'Буйрутма',
                'verbose_name_plural': 'Буйрутмалар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Аталышы')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True, verbose_name='URL Аты (автоматтык)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Сүрөттөмөсү')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баасы (сом)')),
                ('weight_unit', models.CharField(choices=[('кг', 'кг'), ('г', 'г'), ('л', 'литр'), ('мл', 'мл'), ('даана', 'даана')], default='даана', max_length=20, verbose_name='Өлчөм бирдиги')),
                ('image', models.ImageField(upload_to='product_images/', verbose_name='Сүрөтү')),
                ('discount_percent', models.IntegerField(default=0, verbose_name='Арзандатуу (%)')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярдуубу?')),
                ('stock', models.PositiveIntegerField(default=1, verbose_name='Кампадагы саны')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Кошулган убактысы')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңыртылган убактысы')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category', verbose_name='Категориясы')),
            ],
            options={
                'verbose_name': 'Азык',
                'verbose_name_plural': 'Азыктар',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Саны')),
                ('price_at_order', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сатып алуу баасы')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.order', verbose_name='Буйрутма')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='store.product', verbose_name='Азык')),
            ],
            options={
                'verbose_name': 'Буйрутманын курамы',
                'verbose_name_plural': 'Буйрутманын курамдары',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5, verbose_name='Баасы (1-5)')),
                ('comment', models.TextField(verbose_name='Пикир')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жазылган убактысы')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.product', verbose_name='Азык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Колдонуучу')),
            ],
            options={
                'verbose_name': 'Сын-пикир',
                'verbose_name_plural': 'Сын-пикирлер',
                'ordering': ['-created_at'],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
